[package]
name = "kvstore"
version = "0.1.0"
authors = ["Danielius <danieliusvisockas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 'z'

[dependencies]
